spring.application.name=golf-strokes-gained
spring.datasource.url=jdbc:postgresql://localhost:5432/strokes_gained
spring.datasource.username=allenting
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
