package com.golf.golf.strokes.gained.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class UserShot {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private Integer startDist;
    private String startLie;
    private Integer endDist;
    private String endLie;
    private String clubUsed;
    private Integer penaltyStrokes;

    // output
    private Double strokesGained;

    // empty default constructor
    public UserShot() {
    }
    
    public UserShot(Integer startDist, String startLie, Integer endDist, String endLie,
                    Integer penaltyStrokes, String clubUsed, Double strokesGained) {
        this.startDist = startDist;
        this.startLie = startLie;
        this.endDist = endDist;
        this.endLie = endLie;
        this.penaltyStrokes = penaltyStrokes;
        this.clubUsed = clubUsed;
        this.strokesGained = strokesGained;
    }

    // --- GETTERS AND SETTERS ---

    public Long getId() {
        return id;
    }
    // No setId() provided to protect the primary key generated by PostgreSQL

    public Integer getStartDist() {
        return startDist;
    }

    public void setStartDist(Integer startDist) {
        this.startDist = startDist;
    }

    public String getStartLie() {
        return startLie;
    }

    public void setStartLie(String startLie) {
        this.startLie = startLie;
    }

    public Integer getEndDist() {
        return endDist;
    }

    public void setEndDist(Integer endDist) {
        this.endDist = endDist;
    }

    public String getEndLie() {
        return endLie;
    }

    public void setEndLie(String endLie) {
        this.endLie = endLie;
    }

    public String getClubUsed() {
        return clubUsed;
    }

    public void setClubUsed(String clubUsed) {
        this.clubUsed = clubUsed;
    }

    public Integer getPenaltyStrokes() {
        return penaltyStrokes;
    }

    public void setPenaltyStrokes(Integer penaltyStrokes) {
        this.penaltyStrokes = penaltyStrokes;
    }

    public Double getStrokesGained() {
        return strokesGained;
    }

    public void setStrokesGained(Double strokesGained) {
        this.strokesGained = strokesGained;
    }
}