-- Generated by tools/slice_holes.py -- do not hand-edit; rerun the script.
-- Imagery: Esri World Imagery. Hole coordinates: (c) OpenStreetMap contributors.

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole01.jpg',
       37.4235020, -122.1838125, 351.9424, 0.2, 2196, 4392,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 1;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole02.jpg',
       37.4267275, -122.1866310, 295.7390, 0.2, 2018, 4035,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 2;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole03.jpg',
       37.4278895, -122.1894400, 217.2955, 0.2, 927, 1855,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 3;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole04.jpg',
       37.4261845, -122.1908485, 188.2309, 0.2, 784, 1569,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 4;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole05.jpg',
       37.4260705, -122.1894955, 77.1224, 0.2, 1934, 3867,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 5;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole06.jpg',
       37.4249520, -122.1865030, 171.3462, 0.2, 1870, 3740,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 6;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole07.jpg',
       37.4237605, -122.1883365, 300.2244, 0.2, 2089, 4179,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 7;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole08.jpg',
       37.4238710, -122.1906220, 95.8255, 0.2, 833, 1666,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 8;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole09.jpg',
       37.4224770, -122.1881270, 144.0592, 0.2, 1484, 2968,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 9;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole10.jpg',
       37.4203875, -122.1856030, 148.4283, 0.2, 1874, 3747,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 10;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole11.jpg',
       37.4197080, -122.1855685, 327.9770, 0.2, 1505, 3011,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 11;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole12.jpg',
       37.4222185, -122.1888570, 312.0795, 0.2, 2054, 4108,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 12;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole13.jpg',
       37.4223460, -122.1904795, 149.1707, 0.2, 1866, 3732,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 13;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole14.jpg',
       37.4204875, -122.1882185, 87.0481, 0.2, 827, 1654,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 14;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole15.jpg',
       37.4191655, -122.1881275, 230.1730, 0.2, 1477, 2954,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 15;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole16.jpg',
       37.4177460, -122.1868870, 92.2709, 0.2, 2135, 4270,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 16;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole17.jpg',
       37.4167690, -122.1837370, 100.9241, 0.2, 838, 1675,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 17;

INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole18.jpg',
       37.4189515, -122.1835410, 337.9155, 0.2, 1968, 3936,
       'Esri, Vantor, Earthstar Geographics, and the GIS User Community'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = 'Stanford Golf Course' AND h.hole_number = 18;