"""Slice the stitched course master into one rotated image per hole.

Each output is oriented so the hole plays bottom-to-top: tee at bottom-centre,
green at top-centre. Also writes the hole_map seed migration straight into
src/main/resources/db/migration/.

All paths are resolved relative to this script, so it runs from any directory.
"""
import json, math, os
from PIL import Image
Image.MAX_IMAGE_PIXELS = None

HERE = os.path.dirname(os.path.abspath(__file__))

# ---- must match courseMapMaker.py ---------------------------------------
LA0, LA1 = 37.41240, 37.43240
LO0, LO1 = -122.19615, -122.17815
GROUND_MPP = 0.20
MASTER = os.path.join(HERE, "stanfordCourse.jpg")

# ---- framing -------------------------------------------------------------
PAD_FRAC   = 0.45    # padding at each end, as a fraction of hole length
PAD_MIN    = 80.0    # metres, floor so short par 3s aren't cramped
ASPECT     = 0.50    # width / height
MIN_WIDTH  = 100.0   # metres, floor for short holes
OUTDIR     = os.path.join(HERE, "holes")
SQL_OUT    = os.path.normpath(os.path.join(
                 HERE, "..", "src", "main", "resources", "db", "migration",
                 "V6__seed_stanford_maps.sql"))
COURSE     = "Stanford Golf Course"
SOURCE     = "Esri, Vantor, Earthstar Geographics, and the GIS User Community"

R = 6378137
def merc(lat, lng):
    return (R*math.radians(lng), R*math.log(math.tan(math.pi/4 + math.radians(lat)/2)))
x0, y0 = merc(LA0, LO0)
x1, y1 = merc(LA1, LO1)
mpp_merc = GROUND_MPP / math.cos(math.radians((LA0+LA1)/2))
def to_px(lat, lng):
    mx, my = merc(lat, lng)
    return ((mx-x0)/mpp_merc, (y1-my)/mpp_merc)

os.makedirs(OUTDIR, exist_ok=True)
master = Image.open(MASTER)
holes = json.load(open(os.path.join(HERE, "holes.json")))
holes["5"]["tee"] = [37.425663, -122.191740]      # corrected: OSM ref=5 tee polygon

sql = []
for n in range(1, 19):
    tee, grn = holes[str(n)]["tee"], holes[str(n)]["green"]
    pt, pg = to_px(*tee), to_px(*grn)
    Lpx = math.hypot(pg[0]-pt[0], pg[1]-pt[1])
    L_m = Lpx * GROUND_MPP
    # bearing of the line of play, clockwise from north, in image space
    brg = (math.degrees(math.atan2(pg[0]-pt[0], -(pg[1]-pt[1]))) + 360) % 360

    pad = max(PAD_MIN, PAD_FRAC*L_m)
    H_m = L_m + 2*pad
    W_m = max(MIN_WIDTH, H_m*ASPECT)
    Hpx, Wpx = round(H_m/GROUND_MPP), round(W_m/GROUND_MPP)

    # padding is symmetric, so the image centre is the tee-green midpoint
    clat, clng = (tee[0]+grn[0])/2, (tee[1]+grn[1])/2

    cx, cy = to_px(clat, clng)
    half = int(math.hypot(Wpx, Hpx)/2) + 4
    sq = master.crop((int(cx)-half, int(cy)-half, int(cx)+half, int(cy)+half))
    sq = sq.rotate(brg, resample=Image.BICUBIC)     # CCW by bearing -> hole points up
    c = sq.width//2
    crop = sq.crop((c-Wpx//2, c-Hpx//2, c-Wpx//2+Wpx, c-Hpx//2+Hpx))
    path = os.path.join(OUTDIR, f"hole{n:02d}.jpg")
    crop.save(path, quality=90)
    print(f"hole {n:>2}  {Wpx:>4}x{Hpx:<5} px  {L_m:>5.0f} m play  bearing {brg:>5.1f}")

    sql.append(
f"""INSERT INTO hole_map (hole_id, image_path, center_lat, center_lng,
                      bearing_deg, m_per_px, width_px, height_px, imagery_source)
SELECT h.id, '/maps/stanford/hole{n:02d}.jpg',
       {clat:.7f}, {clng:.7f}, {brg:.4f}, {GROUND_MPP}, {Wpx}, {Hpx},
       '{SOURCE}'
FROM hole h JOIN course c ON c.id = h.course_id
WHERE c.name = '{COURSE}' AND h.hole_number = {n};""")

open(SQL_OUT, "w").write(
    "-- Generated by tools/slice_holes.py -- do not hand-edit; rerun the script.\n"
    "-- Imagery: Esri World Imagery. Hole coordinates: (c) OpenStreetMap contributors.\n\n"
    + "\n\n".join(sql) + "\n")
print(f"\nwrote {SQL_OUT}")
print("NOTE: if V6 has already been applied, Flyway will reject the new checksum.")